version: '3'
services:
  postgres-database:
    container_name: postgres-database
    restart: always
    image: postgres:alpine
    ports:
      - 5432:5432
    volumes:
      - $HOME/docker/volumes/postgres1:/var/lib/postgresql/data
      - ./postgres-seed:/docker-entrypoint-initdb.d #run these scripts on first container creation
    environment: 
      - POSTGRES_PASSWORD=docker
  pgweb:
    container_name: pgweb  # optional
    restart: always  # optional
    image: sosedoff/pgweb
    ports: 
      - "8081:8081" 
    links: 
      - postgres-database:db  # my database container is called postgres, not db
    environment:
      - DATABASE_URL=postgres://postgres:docker@db:5432/postgres?sslmode=disable
    depends_on:
      - postgres-database # my database container is called postgres, not db